theme: jekyll-theme-minimal
include:
  - _layouts
  - _includes
  - assets/css

title: "Byunguk Kim's personal webpage"
description: "This is the personal website of Byunguk Kim, PhD candidate in Coastal Engineering Laboratory at Seoul National University."

email: "kim.byunguk@snu.ac.kr"
website: "https://bkim-git.github.io"
affiliation: "Department of Civil & Environmental Engineering, Seoul National University, Seoul, South Korea"
github_link: "https://github.com/Bkim-git"
website: "https://www.researchgate.net/profile/Byunguk-Kim"
google_scholar: "https://scholar.google.com/citations?hl=ko&user=wT66tyUAAAAJ"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
