theme: jekyll-theme-minimal
include:
  - _layouts
  - _includes
  - assets/css

title: "B Kim's personal webpage"
description: "A Jekyll site with a customized minimal theme"
baseurl: "" # Leave empty for user.github.io; change for project sites
url: "https://username.github.io"
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
