theme: jekyll-theme-minimal
include:
  - _layouts
  - _includes
  - assets/css

title: "Byunguk Kim's personal webpage"
description: "A Jekyll site with a customized minimal theme"
email: "kim.byunguk@snu.ac.kr"
affiliation: "Seoul National University"
github_link: "https://github.com/Bkim-git"
baseurl: "" # Leave empty for user.github.io; change for project sites
url: "https://username.github.io"
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
